### ISSUE TITLE
Pressing 'generate word' reloads the model/vocabulary each time

### ISSUE THREAD

**Issue by annaproxy** [Sasafrass/straattaal#21]
This should probably be optimized - only load the current model/dataset once.

But I don't know how to do it in a flask-pythonic way ;)

**Comment by Sasafrass** [comment]
We now have a session object which should be available globally with ```from flask import session```. This can be used in similar fashion as a dictionary and should allow us to store and access a model in a single session without having to reload it each time.

**Comment by Sasafrass** [comment]
This is a little bit trickier than I initially thought. Storing the model in the session in the generate_slang function appears not to work. Possible causes:
* Storing a full PyTorch model or our own Vocabulary object in a session is not possible.
* The API call to /api/generate_slang results in a new session object to be instantiated, ignoring our stored session.
* Filesystem version of the session instead of the redis-server version.

Currently investigating the second option.

**Comment by Sasafrass** [comment]
The following PR should fix it: https://github.com/Sasafrass/straattaal/pull/52
